services:
  mariadb:
    build: ./requirements/mariadb/

    image: mariadb
    container_name: mariadb
    env_file:
    - .env

    networks:
    - inception
    volumes:
    - maria_data:/var/lib/mysql
    restart: always


  wordpress:
    build: ./requirements/wordpress/
    depends_on:
    - mariadb
    image: wordpress
    container_name: wordpress
    env_file:
    - .env
    networks:
    - inception
    volumes:
    - wordpress_data:/var/www/wordpress
    restart: always



  nginx:
    build: ./requirements/nginx/
    image: nginx
    container_name: nginx
    ports:
    - "443:443"
    depends_on:
    - wordpress
    networks:
    - inception
    volumes:
    - wordpress_data:/var/www/wordpress
    restart: always

networks:
    inception:
      driver: bridge

volumes:
 maria_data:
 wordpress_data:
