#version: "3.8"

services:
  mariadb:
    build: ./requirements/mariadb/
    ports:
    -  "3306:3306"

    environment:
       MYSQL_ROOT_PASSWORD: rootpass
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wp_user
       MYSQL_PASSWORD: wp_pass

    networks:
    - inception
 #   volumes:
##    - maria_data:/var/lib/mysql
    restart: unless-stopped


  wordpress:
    ports: 
    - "9000:9000"
    build: ./requirements/wordpress/
    depends_on:
    - mariadb
    networks:
    - inception
 #   volumes:
  #  - wordpress_data:/var/www/wordpress
    restart: unless-stopped



  nginx:
    build: ./requirements/nginx/
    ports:
    - "4443:443"
    depends_on:
    - wordpress
    networks:
    - inception
    restart: unless-stopped

networks:
    inception:
      driver: bridge

#volumes:
# maria_data:
# wordpress_data:
