services:
  mariadb:
    build: ./requirements/mariadb/

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    networks:
    - inception
    volumes:
    - maria_data:/var/lib/mysql
    restart: unless-stopped


  wordpress:
    build: ./requirements/wordpress/
    depends_on:
    - mariadb
    environment:
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MY_DOMAIN_NAME: ${MY_DOMAIN_NAME}
    networks:
    - inception
    volumes:
    - wordpress_data:/var/www/wordpress
    restart: unless-stopped



  nginx:
    build: ./requirements/nginx/
    ports:
    - "4443:443"
    depends_on:
    - wordpress
    networks:
    - inception
    volumes:
    - wordpress_data:/var/www/wordpress
    restart: unless-stopped

networks:
    inception:
      driver: bridge

volumes:
 maria_data:
 wordpress_data:
